### ISSUE TITLE
AppImage fails to sign code on ArchLinux

### ISSUE THREAD

**Issue by SolarAquarion** [LucaT1/yat#16]

**Comment by lucat1** [comment]
Could you please paste here the error trace or some log found in the devtool?

**Comment by SolarAquarion** [comment]
rror: Exit code: 127. Command failed: /home/solaraquarion/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/solaraquarion/yat/build/yat-0.1.4-i386.AppImage -padding 0 -map /home/solaraquarion/yat/build/linux-ia32-unpacked /usr/bin -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/AppRun.sh /AppRun -map /tmp/electron-builder-d9DsHD/0-1-yat.desktop /yat.desktop -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/128x128.png /usr/share/icons/default/128x128/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/16x16.png /usr/share/icons/default/16x16/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/24x24.png /usr/share/icons/default/24x24/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/256x256.png /usr/share/icons/default/256x256/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/32x32.png /usr/share/icons/default/32x32/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/48x48.png /usr/share/icons/default/48x48/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/64x64.png /usr/share/icons/default/64x64/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/96x96.png /usr/share/icons/default/96x96/apps/yat.png -map /home/solaraquarion/yat/node_modules/electron-builder/templates/linux/electron-icons/256x256.png /.DirIcon -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/solaraquarion/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

/home/solaraquarion/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

    at /home/solaraquarion/yat/node_modules/electron-builder-util/src/util.ts:64:16
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
From previous event:
    at exec (/home/solaraquarion/yat/node_modules/electron-builder-util/src/util.ts:42:3)
    at /home/solaraquarion/yat/node_modules/electron-builder/src/targets/appImage.ts:78:5
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/home/solaraquarion/yat/node_modules/electron-builder/out/targets/appImage.js:138:11)
    at taskManager.addTask.default.map.it (/home/solaraquarion/yat/node_modules/electron-builder/src/platformPackager.ts:105:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/solaraquarion/yat/node_modules/electron-builder/src/platformPackager.ts:105:41)
    at /home/solaraquarion/yat/node_modules/electron-builder/src/platformPackager.ts:101:10
From previous event:
    at LinuxPackager.pack (/home/solaraquarion/yat/node_modules/electron-builder/out/platformPackager.js:171:11)
    at /home/solaraquarion/yat/node_modules/electron-builder/src/packager.ts:244:24
From previous event:
    at Packager.doBuild (/home/solaraquarion/yat/node_modules/electron-builder/out/packager.js:317:11)
    at /home/solaraquarion/yat/node_modules/electron-builder/src/packager.ts:175:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Packager.build (/home/solaraquarion/yat/node_modules/electron-builder/out/packager.js:236:11)
    at /home/solaraquarion/yat/node_modules/electron-builder/src/builder.ts:266:40
    at Generator.next (<anonymous>)
    at build (/home/solaraquarion/yat/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/home/solaraquarion/yat/node_modules/electron-builder/src/cli/cli.ts:46:4)
    at Object.self.runCommand (/home/solaraquarion/yat/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/solaraquarion/yat/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/solaraquarion/yat/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/solaraquarion/yat/node_modules/electron-builder/src/cli/cli.ts:41:15)
From previous event:
    at build (/home/solaraquarion/yat/node_modules/electron-builder/out/builder.js:69:21)
    at Object.args [as handler] (/home/solaraquarion/yat/node_modules/electron-builder/out/cli/cli.js:121:9)
    at Object.self.runCommand (/home/solaraquarion/yat/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/home/solaraquarion/yat/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/home/solaraquarion/yat/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/home/solaraquarion/yat/node_modules/electron-builder/out/cli/cli.js:117:465)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by lucat1** [comment]
I'll see if I can reproduce this in a plain Arch Linux VM. What version did you download?

**Comment by SolarAquarion** [comment]
I downloaded it as it uses

>/home/solaraquarion/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

**Comment by lucat1** [comment]
Yes but seeing this:
`rror: Exit code: 127. Command failed: /home/solaraquarion/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso`
Made me wonder if you cloned the repo and tried to build it, or if you downloaded a precompile binary as the title says(or at least means)

**Comment by SolarAquarion** [comment]
I cloned this repo and tried to build the Linux version

On Jul 25, 2017 12:23 PM, "Luca" <notifications@github.com> wrote:

Yes but seeing this:
rror: Exit code: 127. Command failed: /home/solaraquarion/.cache/
electron-builder/AppImage/AppImage-09-07-16-linux/xorriso
Made me wonder if you cloned the repo and tried to build it, or if you
downloaded a precompile binary as the title says(or at least means)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LucaT1/yat/issues/16#issuecomment-317790857>, or mute
the thread

**Comment by lucat1** [comment]
Yes i see. Then you need to refer to [this issue](https://github.com/electron-userland/electron-builder/issues/993) on electron-builder.
You may need to install the `xorriso` package, so try with:

`sudo pacman -S xorriso`
or if you want to update your mirrors and have the latest package:
`sudo pacman -Syy xorriso`

**Comment by SolarAquarion** [comment]
So the ideal would just be ln -s'ing it.  Can't it be done as part of it

On Jul 25, 2017 12:45 PM, "Luca" <notifications@github.com> wrote:

Yes i see. Then you need to refer to this issue
<https://github.com/electron-userland/electron-builder/issues/993> on
electron-builder.
You may need to install the xorriso package, so try with:

sudo pacman -S xorriso
or if you want to update your mirrors and have the latest package:
sudo pacman -Syy xorriso

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LucaT1/yat/issues/16#issuecomment-317796893>, or mute
the thread

**Comment by lucat1** [comment]
First it's an upstream problem of `electron-builder` and secondly, I think it's related to a non-updated symlink or a breaking change in one of xorriso versions. The best that I can do for this repo is to pin this in the issues so that other people can see it. But since it's upstream I can't really do anything.

Anyway if you can tell me the fix you used I can also put it into the README among the other installation instructions

**Comment by SolarAquarion** [comment]
I can do the symlinking in my packaging I guess

**Comment by lucat1** [comment]
Yes i think so, anyway the problem is only related to Arch Linux and the specific binary/version of xorriso that's shipped on Arch since builds are going flawlessly on CI(ubuntu 14).

For your specific issue try to read/comment on the [electron-builder upstream issue](https://github.com/electron-userland/electron-builder/issues/993).

EDIT:
Updated title to describe the issue better.
